Update verify-jira-issue-in-commit-message.yml

diff --git a/.github/workflows/verify-jira-issue-in-commit-message.yml b/.github/workflows/verify-jira-issue-in-commit-message.yml
--- a/.github/workflows/verify-jira-issue-in-commit-message.yml
+++ b/.github/workflows/verify-jira-issue-in-commit-message.yml
@@ -24,15 +24,14 @@ jobs:
           # Regex pattern to match Jira issue keys
           jira_key_regex="($jira_keys[0-9]+)"
           
-          # Loop through commits
+          # If it's a push event (to main/master), check the latest commit
           if [[ $GITHUB_EVENT_NAME == "push" ]]; then
-            # If it's a push event (to main/master), check all commits in the push
-            for commit in $(git log --format="%s" HEAD^1..HEAD); do
-              if [[ ! "$commit" =~ $jira_key_regex ]]; then
-                echo "Error: Commit message '$commit' is missing a valid Jira issue key."
-                exit 1
-              fi
-            done
+            # Get the latest commit message
+            commit_message=$(git log -1 --pretty=%B)
+            if [[ ! "$commit_message" =~ $jira_key_regex ]]; then
+              echo "Error: Commit message '$commit_message' is missing a valid Jira issue key."
+              exit 1
+            fi
           else
             # For pull requests, check the commits in the PR
             for commit in $(git log --format="%s" origin/main..HEAD); do
